---
- name: restart cron
  service:
    name: 'cron'
    state: 'restarted'

- name: restart rsyslog
  service:
    name: 'rsyslog'
    state: 'restarted'

- name: restart incron
  service:
    name: 'incron'
    state: 'restarted'
